biasharahub/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.flatpages.views import flatpage
from django.contrib.sitemaps.views import index, sitemap
from django.urls import path, include

from biasharahub.views import Home, NewsletterView
from business.sitemaps import BusinessSitemap
from reviews.sitemaps import ReviewSitemap

sitemaps = {
    'business': BusinessSitemap,
    'review': ReviewSitemap,

}
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home.as_view(), name='home'),
    path('newsletter', NewsletterView.as_view(), name='newsletter'),
    path('accounts/', include('allauth.urls',)),
    path('accounts/', include('accounts.urls', namespace='accounts')),
    path('categories/', include('categories.urls', namespace='categories')),
    path('business/', include('business.urls', namespace='business')),
    path('reviews/', include('reviews.urls', namespace='reviews')),
    path('comments/', include('comments.urls', namespace='comments')),
    path('invitations/', include('invitations.urls', namespace='invitations')),
    path('locations/', include('locations.urls', namespace='locations')),
    path('opening-hours/', include('openinghours.urls', namespace='openinghours')),
    # path('review-search/', include('haystack.urls')),
    path('about-us/', flatpage, {'url': '/about-us/'}, name='about'),
    path('contact-us/', flatpage, {'url': '/contact-us/'}, name='contact'),
    path('policy/', flatpage, {'url': '/policy/'}, name='policy'),

    path('sitemap.xml', index, {'sitemaps': sitemaps}),
    path('sitemap-<section>.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

business/urls.py
from django.urls import path

from favourites.views import bookmark_company
from .views import BusinessCreate, BusinessDetail, BusinessList, BusinessEdit, add_photos, autocomplete, \
    FacetedSearchView, PhotoGallery, ClaimBusiness

app_name = 'business'

urlpatterns = [
    path('new/', BusinessCreate.as_view(), name='new'),
    path('list/', BusinessList.as_view(), name='list'),

    path('', FacetedSearchView.as_view(), name='search'),

    path('<slug:slug>/', BusinessDetail.as_view(), name='detail'),
    path('<slug:slug>/edit/', BusinessEdit.as_view(), name='edit'),
    path('<slug:slug>/claim/', ClaimBusiness.as_view(), name='claim'),
    path('<slug:slug>/add_photos/', add_photos, name='photos'),
    path('<slug:slug>/gallery/', PhotoGallery.as_view(), name='gallery'),
    path('<slug:slug>/bookmark/', bookmark_company, name='bookmark'),
    path('autocomplete/', autocomplete),


]

reviews/urls.py
from django.urls import path

from favourites.views import vote_up, vote_down, ReviewVoteUp
from .views import ReviewList, ReviewDetail, ReviewCreate, ReviewEdit, photos

app_name = 'reviews'

urlpatterns = [
    path('', ReviewList.as_view(), name='list'),
    path('<slug:slug>/', ReviewDetail.as_view(), name='detail'),
    path('<slug:slug>/new/', ReviewCreate.as_view(), name='new'),
    path('<slug:slug>/edit/', ReviewEdit.as_view(), name='edit'),
    path('<slug:slug>/photos/', photos, name='photos'),
    path('<slug:slug>/review_like/', ReviewVoteUp.as_view(), name='review_like'),
    path('<slug:slug>/vote_up/', vote_up, name='vote_up'),
    path('<slug:slug>/vote_down/', vote_down, name='vote_down'),

]

business/forms.py
from builtins import super

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Column, Layout, Row, Submit
from django import forms
# from django.contrib.admin import widgets
from django.core.checks import Tags
from django.forms import inlineformset_factory, ModelForm
from django.utils.translation import ugettext_lazy as _
from haystack.forms import FacetedSearchForm
from pagedown.widgets import PagedownWidget

from business.models import Business, BusinessImage
from categories.models import Category
from locations.models import Location
from reviews.models import RATING_CHOICES


class BusinessForm(ModelForm):
    logo = forms.ImageField(label='logo', required=False,
                            widget=forms.ClearableFileInput(attrs={'placeholder': 'Logo',
                                                                   'class': 'btn btn-outline-secondary'}))
    description = forms.CharField(widget=PagedownWidget())

    class Meta:
        model = Business
        fields = (
            'name', 'logo', 'description', 'website', 'twitter', 'location', 'category', 'email', 'address', 'services')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_class = 'form-horizontal'
        self.helper.label_class = 'col-lg-2'
        self.helper.field_class = 'col-lg-8'
        self.helper.form_method = 'post'
        self.helper.form_action = 'submit'
        self.helper.add_input(Submit('submit', 'Submit', css_class='btn btn-gradient btn-gradient-two btn-lg'))
        self.helper.layout = Layout(
            'name',
            'logo',
            'description',
            'website',
            'twitter',
            'location',
            'category',
            'email',
            'address',
            'services',
        )


class BusinessFilterForm(forms.Form):
    category = forms.ModelChoiceField(
        label=_("Category"), required=False, queryset=Category.objects.all(),
    )
    location = forms.ModelChoiceField(label=_("Location"), required=False, queryset=Location.objects.all(), )
    rating = forms.ChoiceField(label=_("Rating"), required=False, choices=RATING_CHOICES, )


class ClaimBusinessForm(ModelForm):
    class Meta:
        model = Business
        fields = ('owner',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.layout = Layout(
            'owner',
            Submit('submit', 'Submit'),
        )


BusinessPhotoFormSet = inlineformset_factory(Business, BusinessImage, fields=('img', 'alt'),
                                             widgets={'img': forms.FileInput(attrs={
                                                 'class': 'form-control',
                                                 'placeholder': 'Upload photo Image'
                                             }),
                                                 'alt': forms.TextInput(attrs={
                                                     'class': 'form-control',
                                                     'placeholder': 'Describe image'
                                                 })},
                                             labels={'img': '',
                                                     'alt': ''},
                                             form=BusinessForm, extra=6, max_num=24, can_delete=True)


class BusinessPhotoFormSetHelper(FormHelper):
    def __init__(self, *args, **kwargs):
        super(BusinessPhotoFormSetHelper, self).__init__(*args, **kwargs)
        self.form_method = 'post'
        self.layout = Layout(
            Row(
                Column('img', css_class='mt-10 form-group col-md-4 mb-0'),
                Column('alt', css_class='mt-10 form-group col-md-4 mb-0'),
                css_class='form-row'
            ),
        )
        self.add_input(Submit("submit", "Save", css_class='btn btn-gradient btn-gradient-one'))


class BusinessSearchForm(FacetedSearchForm):

    def __init__(self, *args, **kwargs):
        data = dict(kwargs.get("data", []))
        self.category = data.get('category', [])
        self.location = data.get('location', [])
        super(BusinessSearchForm, self).__init__(*args, **kwargs)

    def search(self):
        sqs = super().search()
        if self.category:
            query = None
            for category in self.category:
                if query:
                    query += u' OR '
                else:
                    query = u''
                query += u'"%s"' % sqs.query.clean(category)
            sqs = sqs.narrow(u'category_exact:%s' % query)
        if self.location:
            query = None
            for location in self.location:
                if query:
                    query += u' OR '
                else:
                    query = u''
                query += u'"%s"' % sqs.query.clean(location)
            sqs = sqs.narrow(u'location_exact:%s' % query)
        return sqs

business/views.py
import warnings

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.sites.shortcuts import get_current_site
from django.core.exceptions import PermissionDenied
from django.core.mail import send_mail
from django.http import JsonResponse, HttpResponseRedirect
from django.http import request
from django.shortcuts import render
from django.views.generic import CreateView, ListView, UpdateView
from django.views.generic.detail import SingleObjectMixin, DetailView
from haystack.generic_views import FacetedSearchView as BaseFacetedSearchView
from haystack.query import SearchQuerySet
from hitcount.models import HitCount
from hitcount.utils import RemovedInHitCount13Warning
from hitcount.views import HitCountMixin

from business.models import Business, BusinessImage
from comments.forms import CommentForm
from reviews.forms import ReviewForm
from .forms import BusinessForm, BusinessPhotoFormSet, BusinessPhotoFormSetHelper, BusinessSearchForm, ClaimBusinessForm


def autocomplete(request):
    sqs = SearchQuerySet().autocomplete(
        content_auto=request.GET.get(
            'query',
            ''))[
          :5]
    s = []
    for result in sqs:
        d = {"value": result.name, "data": result.object.slug}
        s.append(d)
    output = {'suggestions': s}
    return JsonResponse(output)


class FacetedSearchView(BaseFacetedSearchView):
    form_class = BusinessSearchForm
    facet_fields = ['category', 'location']
    template_name = 'business/search_result.html'
    paginate_by = 10
    context_object_name = 'object_list'


class BusinessList(ListView):
    model = Business
    paginate_by = 10
    context_object_name = "business"
    template_name = 'business/list.html'


class BusinessCreate(LoginRequiredMixin, CreateView):
    model = Business
    form_class = BusinessForm
    template_name = 'business/form.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        form.save()
        current_site = get_current_site(request)
        subject = '%s added to %s ' % (form.instance.name, current_site.name)
        message = 'Welcome to %s, %s was added ' \
                  'successfully, you can claim it here %s' % (
                      current_site.name, form.instance.name, form.instance.get_url)
        sender = form.instance.user.email
        recipients = form.instance.email
        send_mail(subject, message, sender, [recipients])
        return super().form_valid(form)


@login_required
def add_photos(request, slug):
    """company = get_object_or_404(Business, slug=slug)"""
    company = Business.objects.get(slug=slug)
    form = BusinessPhotoFormSet(request.POST or None, request.FILES or None, instance=company)
    helper = BusinessPhotoFormSetHelper()

    # if not company.owner:
    #     if company.user != request.user or request.user.is_superuser:
    #         raise PermissionDenied
    # elif company.owner != request.user or request.user.is_superuser:
    #     raise PermissionDenied

    if form.is_valid():
        company = form.cleaned_data['company']
        img = form.cleaned_data['img']
        alt = form.cleaned_data['alt']
        gallery = BusinessImage(img=img, company=company, alt=alt)
        # form.save()
        gallery.save()
        messages.success(request, "Successfully Created")
        return HttpResponseRedirect(company.get_absolute_url())
    # else:
    #     return messages.error(request, 'There\'s and error in this form')
    context = {
        "helper": helper,
        "form": form,
    }
    return render(request, "business/formset.html", context)


class ClaimBusiness(LoginRequiredMixin, UpdateView):
    model = Business
    slug_url_kwarg = 'slug'
    form_class = ClaimBusinessForm
    template_name = 'business/form.html'

    # def get_object(self, *args, **kwargs):
    #     obj = super().get_object(*args, **kwargs)
    #     if not obj.owner:
    #         if not obj.user == self.request.user and not self.request.user.is_superuser:
    #             raise PermissionDenied
    #     elif not obj.owner == self.request.user and not self.request.user.is_superuser:
    #         raise PermissionDenied
    #     else:
    #         return obj


class BusinessEdit(LoginRequiredMixin, UpdateView):
    model = Business
    slug_url_kwarg = 'slug'
    form_class = BusinessForm
    template_name = 'business/form.html'

    # def dispatch(self, request, *args, **kwargs):
    #     obj = super().get_object()
    #     if obj.owner is None:
    #         if obj.user != self.request.user or self.request.user.is_superuser:
    #             raise PermissionDenied
    #     elif obj.owner != self.request.user or self.request.user.is_superuser:
    #         raise PermissionDenied
    #     else:
    #         return obj
    #     return super().dispatch(request, *args, **kwargs)


class BusinessDetail(SingleObjectMixin, HitCountMixin, ListView):
    model = Business
    template_name = 'business/detail.html'
    context_object_name = 'business'
    slug_field = 'slug'
    paginate_by = 10
    count_hit = True

    def get(self, request, *args, **kwargs):
        self.object = self.get_object(queryset=Business.objects.all())
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return self.object.reviews.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = ReviewForm()
        context['comment_form'] = CommentForm()
        # context['related_business'] = self.object.services.similar_objects()[:4]

        if self.object:
            hit_count = HitCount.objects.get_for_object(self.object)
            hits = hit_count.hits
            context['hitcount'] = {'pk': hit_count.pk}

            if self.count_hit:
                hit_count_response = self.hit_count(self.request, hit_count)
                if hit_count_response.hit_counted:
                    hits = hits + 1
                context['hitcount']['hit_counted'] = hit_count_response.hit_counted
                context['hitcount']['hit_message'] = hit_count_response.hit_message

            context['hitcount']['total_hits'] = hits

        return context

    def _update_hit_count(request, hitcount):
        """
        Deprecated in 1.2. Use hitcount.views.Hit CountMixin.hit_count() instead.
        """
        warnings.warn(
            "hitcount.views._update_hit_count is deprecated. "
            "Use hitcount.views.HitCountMixin.hit_count() instead.",
            RemovedInHitCount13Warning
        )
        return HitCountMixin.hit_count(request, hitcount)


class PhotoGallery(DetailView):
    model = Business
    template_name = 'business/photo_gallery.html'
    context_object_name = 'photo'

templates/business/list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load hitcount_tags %}

{% block title %}  Biashara List  | {{ block.super }} {% endblock %}

{% block bg-image-holder %}
<div class="bg_image_holder"><img alt="" src='{% static "img/breadcrumb1.jpg" %}'></div>
{% endblock %}

{% block page-title %}
<h1 class="page-title">Biashara List</h1>
{% endblock %}

{% block breadcrumb_item %}
<li class="breadcrumb-item"><a href='{% url "business:new" %}'><i class="fa fa-plus"></i>New</a></li>
<li aria-current="page" class="breadcrumb-item active">All Listings</li>
{% endblock %}

{% block content %}
<section class="all-listing-wrapper section-bg">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="atbd_generic_header">
          <div class="atbd_generic_header_title">
            <h4>All Items</h4>
            <p>Total Biasharas Found: {{ business.count }}</p>
          </div><!-- ends: .atbd_generic_header_title -->
          <div class="atbd_listing_action_btn btn-toolbar align-items-center" role="toolbar">
            <!-- Views dropdown -->
            <!-- Orderby dropdown -->
          </div><!-- ends: .atbd_listing_action_btn -->
        </div><!-- ends: .atbd_generic_header -->
      </div><!-- ends: .col-lg-12 -->
      <div class="col-lg-12 listing-items">
        <div class="row">
          {% include 'includes/side_search_filter.html' %}
          <div class="col-lg-8 order-0 order-lg-1">
            <div class="row">
              {% for business in business %}
              <div class="col-lg-12">
                <div class="atbd_single_listing atbd_listing_list">
                  <article class="atbd_single_listing_wrapper">
                    <figure class="atbd_listing_thumbnail_area">
                      <div class="atbd_listing_image">
                        <a href="{{ business.get_absolute_url }}">
                          <img alt="listing image" src='{% if business.featured_image %}
                          {{ business.featured_image }}
                          {% else %} {% static "img/p1.jpg" %} {% endif %}'>
                        </a>
                      </div><!-- ends: .atbd_listing_image -->
                      <div class="atbd_thumbnail_overlay_content">
                        <ul class="atbd_upper_badge">
                          {% if business.featured %}
                          <li><span class="atbd_badge atbd_badge_featured">Featured</span></li>
                          {% endif %}
                          {% if business.verified %}
                          <li><span class="atbd_badge atbd_badge_popular">Verified</span></li>
                          {% endif %}
                        </ul><!-- ends .atbd_upper_badge -->
                      </div><!-- ends: .atbd_thumbnail_overlay_content -->
                    </figure><!-- ends: .atbd_listing_thumbnail_area -->
                    <div class="atbd_listing_info">
                      <div class="atbd_content_upper">
                        <h4 class="atbd_listing_title">
                          <a href="{{ business.get_url_path }}">{{ business.name }}</a>
                        </h4>
                        <div class="atbd_listing_meta">
                          <span class="atbd_meta atbd_listing_rating">
                                                      {% if business.reviews.count > 3 %}
                            {{ business.average_rating | floatformat }}
                          {% else %}
                          need 3+
                            <i class="la la-star"></i></span>
                          {% endif %}
                          {% comment %}
                          {% if business.is_open and business.closed == False %}
                          <span class="atbd_meta atbd_badge_open">Open Now</span>
                          {% else %}
                          <span class="atbd_meta atbd_badge_close">Closed</span>
                          {% endif %}
                          {% endcomment %}
                        </div><!-- End atbd listing meta -->
                        <div class="atbd_listing_data_list">
                          <ul>
                            {% if business.address %}
                            <li>
                              <p><span class="la la-map-marker"></span>{{ business.address }},
                                {% if business.location %}
                                {{ business.location }}, {{ business.location.country }}
                                {% endif %}
                              </p>
                            </li>
                            {% endif %}
                            <li>
                              {% if business.phone %}
                              <p><span class="la la-phone"></span>(+254) {{ business.phone }}</p>
                              {% endif %}
                            </li>
                            <li>
                              <p><span class="la la-calendar-check-o"></span>
                                Posted {{ business.publish|timesince }} ago ( {{ business.publish|date }} )</p>
                            </li>
                          </ul>
                        </div><!-- End atbd listing meta -->
                      </div><!-- end .atbd_content_upper -->
                      <div class="atbd_listing_bottom_content">
                        <div class="atbd_content_left">
                          <div class="atbd_listing_category">
                            {% if business.category %}
                            <a href=""><span class="{{ business.category.icon }}"></span>{{ business.category }}</a>
                            {% endif %}
                          </div>
                        </div>
                        <ul class="atbd_content_right">
                          <li class="atbd_count"><span class="la la-eye"></span>
                            {% get_hit_count for business %}+
                          </li>
                          <li class="atbd_save">
                            <span href="{% url 'business:bookmark' slug=business.slug %}" class="la la-heart-o"></span>
                          </li>
                          <li>
                            <div class="atbd_author atbd_author--thumb">
                              <a href="{{ business.get_absolute_url }}">
                                <img alt="Logo" src='{% if business.logo %}
                          {{ business.logo.url }} {% else %} {% static "img/author-thumb2.jpg" %} {% endif %}'>
                                <span class="custom-tooltip">{{ business.name }}</span>
                              </a>
                            </div>
                          </li>
                        </ul>
                      </div><!-- end .atbd_listing_bottom_content -->
                    </div><!-- ends: .atbd_listing_info -->
                  </article><!-- atbd_single_listing_wrapper -->
                </div>
              </div><!-- ends: .col-lg-12 -->
              {% endfor %}
            </div>

            {% include 'includes/pagination.html' %}

          </div><!-- ends: .col-lg-8 -->
        </div>
      </div><!-- ends: .listing-items -->
    </div>
  </div>
</section><!-- ends: .all-listing-wrapper -->

{% endblock content %}

templates/business/search_result.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load crispy_forms_tags %}
{% load hitcount_tags %}


{% block title %}  Search {{ query }}  | {{ block.super }} {% endblock %}

{% block bg-image-holder %}
<div class="bg_image_holder"><img alt="" src='{% static "img/breadcrumb1.jpg" %}'></div>
{% endblock %}

{% block page-title %}
<h1 class="page-title">Search {{ query }}</h1>
{% endblock %}

{% block breadcrumb_item %}
<li class="breadcrumb-item"><a href='{% url "business:new" %}'><i class="fa fa-plus"></i>New</a></li>
<li aria-current="page" class="breadcrumb-item active">Search {{ query }}</li>
{% endblock %}


{% block content %}
<section class="all-listing-wrapper section-bg">
  <div class="container">
    <div class="row">
      <div class="col-lg-12">
        <div class="atbd_generic_header">
          <div class="atbd_generic_header_title">
            <h4>All Items</h4>
            <p>Total Biasharas Found: {{ page_obj.paginator.count }} with the term {{ query }}</p>
          </div><!-- ends: .atbd_generic_header_title -->
          <div class="atbd_listing_action_btn btn-toolbar align-items-center" role="toolbar">
            <!-- Views dropdown -->
            <!-- Orderby dropdown -->
          </div><!-- ends: .atbd_listing_action_btn -->
        </div><!-- ends: .atbd_generic_header -->
      </div><!-- ends: .col-lg-12 -->
      {% if page_obj.object_list %}
      <div class="col-lg-12 listing-items">
        <div class="row">
          {% include 'includes/side_search_filter.html' %}
          <div class="col-lg-8 order-0 order-lg-1">
            <div class="row">
              {% for business in page_obj.object_list %}

              <div class="col-lg-12">
                <div class="atbd_single_listing atbd_listing_list">
                  <article class="atbd_single_listing_wrapper">
                    <figure class="atbd_listing_thumbnail_area">
                      <div class="atbd_listing_image">
                        <a href="{{ business.object.get_url_path }}">
                          <img alt="listing image" src='{% if business.featured_image %}
                          {{ business.featured_image }}
                          {% else %} {% static "img/p1.jpg" %} {% endif %}'>
                        </a>
                      </div><!-- ends: .atbd_listing_image -->
                      <div class="atbd_thumbnail_overlay_content">
                        <ul class="atbd_upper_badge">
                          {% if business.featured %}
                          <li><span class="atbd_badge atbd_badge_featured">Featured</span></li>
                          {% endif %}
                          {% if business.verified %}
                          <li><span class="atbd_badge atbd_badge_popular">Verified</span></li>
                          {% endif %}
                        </ul><!-- ends .atbd_upper_badge -->
                      </div><!-- ends: .atbd_thumbnail_overlay_content -->
                    </figure><!-- ends: .atbd_listing_thumbnail_area -->
                    <div class="atbd_listing_info">
                      <div class="atbd_content_upper">
                        <h4 class="atbd_listing_title">
                          <a href="{{ business.object.get_url_path }}">{{ business.name }}</a>
                        </h4>
                        <div class="atbd_listing_meta">
                          <span class="atbd_meta atbd_listing_rating">
                                                      {% if business.reviews.count > 3 %}
                            {{ business.average_rating | floatformat }}
                          {% else %}
                          need 3+
                            <i class="la la-star"></i></span>
                          {% endif %}
                          {% comment %}
                          {% if business.is_open and business.closed == False %}
                          <span class="atbd_meta atbd_badge_open">Open Now</span>
                          {% else %}
                          <span class="atbd_meta atbd_badge_close">Closed</span>
                          {% endif %}
                          {% endcomment %}
                        </div><!-- End atbd listing meta -->
                        <div class="atbd_listing_data_list">
                          <ul>
                            {% if business.address %}
                            <li>
                              <p><span class="la la-map-marker"></span>{{ business.address }},
                                {% if business.location %}
                                {{ business.location }}, {{ business.location.country }}
                                {% endif %}
                              </p>
                            </li>
                            {% endif %}
                            <li>
                              {% if business.phone %}
                              <p><span class="la la-phone"></span>(+254) {{ business.phone }}</p>
                              {% endif %}
                            </li>
                            <li>
                              <p><span class="la la-calendar-check-o"></span>
                                Posted {{ business.publish|timesince }} ago ( {{ business.publish|date }} )</p>
                            </li>
                          </ul>
                        </div><!-- End atbd listing meta -->
                      </div><!-- end .atbd_content_upper -->
                      <div class="atbd_listing_bottom_content">
                        <div class="atbd_content_left">
                          <div class="atbd_listing_category">
                            {% if business.category %}
                            <a href=""><span class="{{ business.category.icon }}"></span>{{ business.category }}</a>
                            {% endif %}
                          </div>
                        </div>
                        <ul class="atbd_content_right">
                          <li class="atbd_save">
                            <span href="{% url 'business:bookmark' slug=business.slug %}" class="la la-heart-o"></span>
                          </li>
                          <li>
                            <div class="atbd_author atbd_author--thumb">
                              <a href="{{ business.object.get_url_path }}">
                                <img alt="Logo" src='{% if business.logo %}
                          {{ business.logo.url }} {% else %} {% static "img/author-thumb2.jpg" %} {% endif %}'>
                                <span class="custom-tooltip">{{ business.name }}</span>
                              </a>
                            </div>
                          </li>
                        </ul>
                      </div><!-- end .atbd_listing_bottom_content -->
                    </div><!-- ends: .atbd_listing_info -->
                  </article><!-- atbd_single_listing_wrapper -->
                </div>
              </div><!-- ends: .col-lg-12 -->
              {% endfor %}
            </div>

            {% if is_paginated %}
            <div class="row">
              <div class="col-lg-12">
                <nav class="navigation pagination d-flex justify-content-end" role="navigation">
                  <div class="nav-links">
                    {% if page_obj.has_previous %}
                    <a class="prev page-numbers" href="?q={{ query }}&page={{ page_obj.previous_page_number }}">
                      <span class="la la-long-arrow-left"></span></a>
                    {% else %}
                    <a class="prev page-numbers disabled"><span class="la la-long-arrow-left"></span></a>
                    {% endif %}
                    {% for i in paginator.page_range %}
                    {% if page_obj.number == i %}
                    <span aria-current="page" class="page-numbers current">{{ i }}</span>
                    {% else %}

                    <a class="page-numbers" href="?q={{ query }}&page={{ i }}">{{ i }}</a>
                    {% endif %}
                    {% endfor %}
                    {% if page_obj.has_next %}
                    <a class="next page-numbers" href="?q={{ query }}&page={{ page_obj.next_page_number }}">
                      <span class="la la-long-arrow-right"></span></a>
                    {% else %}
                    <a class="next page-numbers disabled"><span class="la la-long-arrow-right"></span></a>
                    {% endif %}
                  </div>
                </nav>
              </div>
            </div>
            {% endif %}

            {% else %}
            <p> Sorry, no result found for the search term <strong>{{ query }} </strong></p>
            {% endif %}
          </div><!-- ends: .col-lg-8 -->
        </div>
      </div><!-- ends: .listing-items -->
    </div>
  </div>
</section><!-- ends: .all-listing-wrapper -->

{% endblock %}
    